[package]
name    = "serde-bendy"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"

[dependencies]
bendy = "0.2.2"
serde = "1.0.104"

[dev-dependencies]
serde_derive = "1.0.104"
